/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.imt.pimaua.telas ;

import br.imt.pimaua.Flashcard ;
import br.imt.pimaua.persistencia.FlashcardDAO;
import javax.swing.JOptionPane;
/**
 *
 * @author Ian
 */
public class CriarFlashCardTela extends javax.swing.JFrame {

    /**
     * Creates new form FlashCardTela
     */
    public CriarFlashCardTela() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        voltarButtom = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        enunciadoTextField = new javax.swing.JTextField();
        enunciadoLabel = new javax.swing.JLabel();
        respostaLabel = new javax.swing.JLabel();
        respostaTextField = new javax.swing.JTextField();
        materiaComboBox = new javax.swing.JComboBox<>();
        dificuldadeComboBox = new javax.swing.JComboBox<>();
        criarFlashcardButtom = new javax.swing.JButton();
        visualizarButtom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 198, 76));

        voltarButtom.setBackground(new java.awt.Color(30, 180, 195));
        voltarButtom.setText("voltar");
        voltarButtom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        voltarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtomActionPerformed(evt);
            }
        });

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        enunciadoTextField.setBackground(new java.awt.Color(255, 229, 174));
        enunciadoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enunciadoTextFieldActionPerformed(evt);
            }
        });

        enunciadoLabel.setText("ENUNCIADO:");

        respostaLabel.setText("RESPOSTA:");

        respostaTextField.setBackground(new java.awt.Color(255, 229, 174));
        respostaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respostaTextFieldActionPerformed(evt);
            }
        });

        materiaComboBox.setBackground(new java.awt.Color(255, 229, 174));
        materiaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Matemática", "Lingua Portuguesa", "Física", "Química", "Biologia", "História", "Linguagens" }));
        materiaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiaComboBoxActionPerformed(evt);
            }
        });

        dificuldadeComboBox.setBackground(new java.awt.Color(255, 229, 174));
        dificuldadeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Fácil", "Médio", "Difícil" }));
        dificuldadeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dificuldadeComboBoxActionPerformed(evt);
            }
        });

        criarFlashcardButtom.setBackground(new java.awt.Color(238, 33, 82));
        criarFlashcardButtom.setForeground(new java.awt.Color(255, 255, 255));
        criarFlashcardButtom.setText("CRIAR FLASHCARD");
        criarFlashcardButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarFlashcardButtomActionPerformed(evt);
            }
        });

        visualizarButtom.setText("visualizar");
        visualizarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(enunciadoTextField)
            .addComponent(respostaTextField, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(materiaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dificuldadeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(criarFlashcardButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(respostaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(visualizarButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(enunciadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materiaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dificuldadeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(enunciadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enunciadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respostaLabel)
                    .addComponent(visualizarButtom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(respostaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(criarFlashcardButtom, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(voltarButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(voltarButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enunciadoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enunciadoTextFieldActionPerformed
        // nesse campo o usuario ira inserir a PERGUNTA do flashcard
        String pergunta = enunciadoTextField.getText() ;
    }//GEN-LAST:event_enunciadoTextFieldActionPerformed

    private void respostaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respostaTextFieldActionPerformed
        // nesse campo o usuario ira inserir a RESPOSTA do flashcard
        String resposta = respostaTextField.getText() ;
    }//GEN-LAST:event_respostaTextFieldActionPerformed

    private void criarFlashcardButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarFlashcardButtomActionPerformed
        // responsavel por criar o flashcard (ira jogar os dados preenchidos para o banco de dados)

        String pergunta = enunciadoTextField.getText() ;
        String resposta = respostaTextField.getText() ;
        var dificuldade = dificuldadeComboBox.getSelectedItem() ;
        var materia = materiaComboBox.getSelectedItem() ;
        
        var flashcard = new Flashcard(resposta, pergunta, dificuldade, materia);
        try {
            FlashcardDAO dao = new FlashcardDAO() ;
            dao.cadastrar(flashcard) ;
            
        } catch (Exception e){
            
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar: ");
        }
        
        
    }//GEN-LAST:event_criarFlashcardButtomActionPerformed
        
    private void visualizarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarButtomActionPerformed
        // a tela do flashcard comecara com setVisible(false) ao clicar nesse botao o respostaTextField.setvisible(true) 
        //esse botaonao eh necessario para a tela de criar flashcard
        setVisible(false) ;
        FlashCardTela flashcard ;
        flashcard = new FlashCardTela();
        flashcard.setVisible(true) ;
    }//GEN-LAST:event_visualizarButtomActionPerformed

    private void dificuldadeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dificuldadeComboBoxActionPerformed
        // o usuario ira escolher a dificulde
    }//GEN-LAST:event_dificuldadeComboBoxActionPerformed

    private void materiaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiaComboBoxActionPerformed
        // jogador ira escolher a materia( para colocar as materias: clicar no combobox->propriets->model-> colocar as materias)
        
    }//GEN-LAST:event_materiaComboBoxActionPerformed

    private void voltarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtomActionPerformed
        this.setVisible(false);
        InicioTela inicio = new InicioTela() ;
        inicio.setVisible(true) ;
    }//GEN-LAST:event_voltarButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

    
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CriarFlashCardTela().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criarFlashcardButtom;
    private javax.swing.JComboBox<String> dificuldadeComboBox;
    private javax.swing.JLabel enunciadoLabel;
    private javax.swing.JTextField enunciadoTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> materiaComboBox;
    private javax.swing.JLabel respostaLabel;
    private javax.swing.JTextField respostaTextField;
    private javax.swing.JButton visualizarButtom;
    private javax.swing.JButton voltarButtom;
    // End of variables declaration//GEN-END:variables

    private static class Dificuldade {

        public Dificuldade() {
        }
    }

    private static class Materia {

        public Materia() {
        }
    }
}
