package br.imt.pimaua.telas;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gustavo M.C
 */
public class JogoTela extends javax.swing.JFrame {

    /**
     * Creates new form JogoTela
     */
    public JogoTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundoJogoPanel = new javax.swing.JPanel();
        linhaVermelhaPanel = new javax.swing.JPanel();
        linhaAzulPanel = new javax.swing.JPanel();
        pararJogoButton = new javax.swing.JButton();
        proxPerguntaButton = new javax.swing.JButton();
        fundoRespostaPanel = new javax.swing.JPanel();
        revelarButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        respostaTextPane = new javax.swing.JTextPane();
        fundoPerguntaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        perguntaTextPane = new javax.swing.JTextPane();
        logoPoliedro = new javax.swing.JLabel();
        voltarButton = new javax.swing.JButton();
        logoPoliedroLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 214, 163));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        fundoJogoPanel.setBackground(new java.awt.Color(255, 255, 0));
        fundoJogoPanel.setLayout(null);

        linhaVermelhaPanel.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout linhaVermelhaPanelLayout = new javax.swing.GroupLayout(linhaVermelhaPanel);
        linhaVermelhaPanel.setLayout(linhaVermelhaPanelLayout);
        linhaVermelhaPanelLayout.setHorizontalGroup(
            linhaVermelhaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        linhaVermelhaPanelLayout.setVerticalGroup(
            linhaVermelhaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        fundoJogoPanel.add(linhaVermelhaPanel);
        linhaVermelhaPanel.setBounds(-7, 490, 680, 30);

        linhaAzulPanel.setBackground(new java.awt.Color(51, 204, 255));

        javax.swing.GroupLayout linhaAzulPanelLayout = new javax.swing.GroupLayout(linhaAzulPanel);
        linhaAzulPanel.setLayout(linhaAzulPanelLayout);
        linhaAzulPanelLayout.setHorizontalGroup(
            linhaAzulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        linhaAzulPanelLayout.setVerticalGroup(
            linhaAzulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        fundoJogoPanel.add(linhaAzulPanel);
        linhaAzulPanel.setBounds(0, 520, 670, 60);

        pararJogoButton.setBackground(new java.awt.Color(255, 0, 0));
        pararJogoButton.setForeground(new java.awt.Color(255, 255, 255));
        pararJogoButton.setText("parar");
        pararJogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pararJogoButtonActionPerformed(evt);
            }
        });
        fundoJogoPanel.add(pararJogoButton);
        pararJogoButton.setBounds(130, 380, 130, 40);

        proxPerguntaButton.setBackground(new java.awt.Color(51, 51, 255));
        proxPerguntaButton.setForeground(new java.awt.Color(255, 255, 255));
        proxPerguntaButton.setText("próxima pregunta");
        proxPerguntaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxPerguntaButtonActionPerformed(evt);
            }
        });
        fundoJogoPanel.add(proxPerguntaButton);
        proxPerguntaButton.setBounds(390, 380, 130, 40);

        fundoRespostaPanel.setBackground(new java.awt.Color(255, 214, 163));
        fundoRespostaPanel.setLayout(null);

        revelarButton.setBackground(new java.awt.Color(255, 214, 163));
        revelarButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 32)); // NOI18N
        revelarButton.setText("👁️");
        revelarButton.setBorder(null);
        revelarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                revelarButtonMouseClicked(evt);
            }
        });
        revelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revelarButtonActionPerformed(evt);
            }
        });
        fundoRespostaPanel.add(revelarButton);
        revelarButton.setBounds(330, 0, 50, 40);

        respostaTextPane.setBackground(new java.awt.Color(255, 214, 160));
        respostaTextPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Resposta"));
        jScrollPane2.setViewportView(respostaTextPane);

        fundoRespostaPanel.add(jScrollPane2);
        jScrollPane2.setBounds(10, 40, 370, 170);

        fundoJogoPanel.add(fundoRespostaPanel);
        fundoRespostaPanel.setBounds(130, 140, 390, 220);

        fundoPerguntaPanel.setBackground(new java.awt.Color(255, 255, 255));

        perguntaTextPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Pergunta"));
        jScrollPane1.setViewportView(perguntaTextPane);

        javax.swing.GroupLayout fundoPerguntaPanelLayout = new javax.swing.GroupLayout(fundoPerguntaPanel);
        fundoPerguntaPanel.setLayout(fundoPerguntaPanelLayout);
        fundoPerguntaPanelLayout.setHorizontalGroup(
            fundoPerguntaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoPerguntaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        fundoPerguntaPanelLayout.setVerticalGroup(
            fundoPerguntaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoPerguntaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fundoJogoPanel.add(fundoPerguntaPanel);
        fundoPerguntaPanel.setBounds(130, 40, 390, 100);

        logoPoliedro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/gmc/pi_1osem/telas/imagens/logo_poliedro.png"))); // NOI18N
        fundoJogoPanel.add(logoPoliedro);
        logoPoliedro.setBounds(570, 20, 0, 0);

        voltarButton.setBackground(new java.awt.Color(255, 255, 0));
        voltarButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        voltarButton.setText("←");
        voltarButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        fundoJogoPanel.add(voltarButton);
        voltarButton.setBounds(20, 20, 50, 40);

        logoPoliedroLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_poliedro.png"))); // NOI18N
        fundoJogoPanel.add(logoPoliedroLabel);
        logoPoliedroLabel.setBounds(560, 20, 60, 80);

        getContentPane().add(fundoJogoPanel);
        fundoJogoPanel.setBounds(-10, 0, 670, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void proxPerguntaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxPerguntaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proxPerguntaButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void pararJogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pararJogoButtonActionPerformed
        dispose();
    }//GEN-LAST:event_pararJogoButtonActionPerformed

    private void revelarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_revelarButtonMouseClicked
        respostaTextPane.setVisible(!respostaTextPane.isVisible());
    }//GEN-LAST:event_revelarButtonMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        respostaTextPane.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void revelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revelarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_revelarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fundoJogoPanel;
    private javax.swing.JPanel fundoPerguntaPanel;
    private javax.swing.JPanel fundoRespostaPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel linhaAzulPanel;
    private javax.swing.JPanel linhaVermelhaPanel;
    private javax.swing.JLabel logoPoliedro;
    private javax.swing.JLabel logoPoliedroLabel;
    private javax.swing.JButton pararJogoButton;
    private javax.swing.JTextPane perguntaTextPane;
    private javax.swing.JButton proxPerguntaButton;
    private javax.swing.JTextPane respostaTextPane;
    private javax.swing.JButton revelarButton;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
