/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.imt.pimaua.telas;

/**
 *
 * @author Gustavo M.C
 */
public class MenuTela extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FundoPanel = new javax.swing.JPanel();
        LinhaAzulPanel = new javax.swing.JPanel();
        LinhaVermelhaPanel = new javax.swing.JPanel();
        LogoPoliedroLabel = new javax.swing.JLabel();
        ModoDeJogoButton = new javax.swing.JButton();
        BaralhosEFlashcardsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FundoPanel.setBackground(new java.awt.Color(255, 255, 0));
        FundoPanel.setLayout(null);

        LinhaAzulPanel.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout LinhaAzulPanelLayout = new javax.swing.GroupLayout(LinhaAzulPanel);
        LinhaAzulPanel.setLayout(LinhaAzulPanelLayout);
        LinhaAzulPanelLayout.setHorizontalGroup(
            LinhaAzulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
        );
        LinhaAzulPanelLayout.setVerticalGroup(
            LinhaAzulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        FundoPanel.add(LinhaAzulPanel);
        LinhaAzulPanel.setBounds(0, 475, 805, 75);

        LinhaVermelhaPanel.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout LinhaVermelhaPanelLayout = new javax.swing.GroupLayout(LinhaVermelhaPanel);
        LinhaVermelhaPanel.setLayout(LinhaVermelhaPanelLayout);
        LinhaVermelhaPanelLayout.setHorizontalGroup(
            LinhaVermelhaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        LinhaVermelhaPanelLayout.setVerticalGroup(
            LinhaVermelhaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        FundoPanel.add(LinhaVermelhaPanel);
        LinhaVermelhaPanel.setBounds(0, 460, 810, 20);

        LogoPoliedroLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/compressed_7.jpg"))); // NOI18N
        LogoPoliedroLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        FundoPanel.add(LogoPoliedroLabel);
        LogoPoliedroLabel.setBounds(170, 30, 420, 170);

        ModoDeJogoButton.setBackground(new java.awt.Color(255, 0, 0));
        ModoDeJogoButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ModoDeJogoButton.setForeground(new java.awt.Color(255, 255, 255));
        ModoDeJogoButton.setText("Modos de jogo");
        ModoDeJogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModoDeJogoButtonActionPerformed(evt);
            }
        });
        FundoPanel.add(ModoDeJogoButton);
        ModoDeJogoButton.setBounds(250, 280, 250, 60);

        BaralhosEFlashcardsButton.setBackground(new java.awt.Color(255, 0, 0));
        BaralhosEFlashcardsButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BaralhosEFlashcardsButton.setForeground(new java.awt.Color(255, 255, 255));
        BaralhosEFlashcardsButton.setText("Baralhos e flashcards");
        BaralhosEFlashcardsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaralhosEFlashcardsButtonActionPerformed(evt);
            }
        });
        FundoPanel.add(BaralhosEFlashcardsButton);
        BaralhosEFlashcardsButton.setBounds(250, 370, 250, 60);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Bem vindo/a ao jogo de flashcards!");
        FundoPanel.add(jLabel1);
        jLabel1.setBounds(200, 220, 380, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FundoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FundoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BaralhosEFlashcardsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaralhosEFlashcardsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BaralhosEFlashcardsButtonActionPerformed

    private void ModoDeJogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModoDeJogoButtonActionPerformed
        this.setVisible(false);
        CriarUsuarioTela criar = new CriarUsuarioTela();
        criar.setVisible(true);
    }//GEN-LAST:event_ModoDeJogoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BaralhosEFlashcardsButton;
    private javax.swing.JPanel FundoPanel;
    private javax.swing.JPanel LinhaAzulPanel;
    private javax.swing.JPanel LinhaVermelhaPanel;
    private javax.swing.JLabel LogoPoliedroLabel;
    private javax.swing.JButton ModoDeJogoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
