
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.imt.pimaua.telas;
import javax.swing.JOptionPane;


/**
 *
 * @author Ian
 */
public class ModoDeJogoTela extends javax.swing.JFrame {
    /**
     * Creates new form ModoDeJogoTela
     */
    public ModoDeJogoTela() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AmareloPanel = new javax.swing.JPanel();
        AzulPanel = new javax.swing.JPanel();
        TituloLabel = new javax.swing.JLabel();
        AleatorioButton = new javax.swing.JButton();
        PorMateriaButton = new javax.swing.JButton();
        DesafioButton = new javax.swing.JButton();
        VoltarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 198, 75));

        AmareloPanel.setBackground(new java.awt.Color(255, 198, 75));
        AmareloPanel.setForeground(new java.awt.Color(255, 196, 77));

        AzulPanel.setBackground(new java.awt.Color(25, 194, 199));

        TituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        TituloLabel.setText("MODO DE JOGO");
        TituloLabel.setMaximumSize(new java.awt.Dimension(180, 32));

        AleatorioButton.setText("Modo aleatório");
        AleatorioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AleatorioButtonActionPerformed(evt);
            }
        });

        PorMateriaButton.setText("Modo por matéria");
        PorMateriaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorMateriaButtonActionPerformed(evt);
            }
        });

        DesafioButton.setText("Modo desafio");
        DesafioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesafioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AzulPanelLayout = new javax.swing.GroupLayout(AzulPanel);
        AzulPanel.setLayout(AzulPanelLayout);
        AzulPanelLayout.setHorizontalGroup(
            AzulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AzulPanelLayout.createSequentialGroup()
                .addGroup(AzulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AzulPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(AzulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PorMateriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AleatorioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DesafioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AzulPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(TituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        AzulPanelLayout.setVerticalGroup(
            AzulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AzulPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AleatorioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PorMateriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(DesafioButton)
                .addGap(23, 23, 23))
        );

        VoltarButton.setBackground(new java.awt.Color(255, 198, 75));
        VoltarButton.setText("Voltar");
        VoltarButton.setBorderPainted(false);
        VoltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AmareloPanelLayout = new javax.swing.GroupLayout(AmareloPanel);
        AmareloPanel.setLayout(AmareloPanelLayout);
        AmareloPanelLayout.setHorizontalGroup(
            AmareloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AmareloPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(AzulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(AmareloPanelLayout.createSequentialGroup()
                .addComponent(VoltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AmareloPanelLayout.setVerticalGroup(
            AmareloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AmareloPanelLayout.createSequentialGroup()
                .addComponent(VoltarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(AzulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AmareloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AmareloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AleatorioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AleatorioButtonActionPerformed
           //new JogoTela("Aleatório").setVisible(true);
        dispose();
    this.setVisible(false);
   
    // Aquivocê pode abrir uma tela de jogo com esse modo
    // Exemplo: new JogoTela("aleatorio").setVisible(true);
    // dispose();


    }//GEN-LAST:event_AleatorioButtonActionPerformed

    private void DesafioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesafioButtonActionPerformed
       
        new ModoDesafioaTela().setVisible(true); // Abre a tela
        dispose(); // Fecha a atual
        this.setVisible(false);
        ModoDesafioaTela Desafio = new ModoDesafioaTela();
        Desafio.setVisible(true);


        
  
    }//GEN-LAST:event_DesafioButtonActionPerformed

    private void VoltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarButtonActionPerformed
        this.setVisible(false);
        InicioTela inicio = new InicioTela() ;
        inicio.setVisible(true) ;
        //nome tela //crio variavel 
         //inicio = new//nome tela()
         //inicio.setVisible(true)// TODO add your handling code here:
    }//GEN-LAST:event_VoltarButtonActionPerformed

    private void PorMateriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorMateriaButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false) ;
        SelecionarMateria materias = new SelecionarMateria() ;
        materias.setVisible(true) ;
    }//GEN-LAST:event_PorMateriaButtonActionPerformed

    /**
     * @param args
     */
    public static void main(String args[]) {
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(ModoDeJogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModoDeJogoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AleatorioButton;
    private javax.swing.JPanel AmareloPanel;
    private javax.swing.JPanel AzulPanel;
    private javax.swing.JButton DesafioButton;
    private javax.swing.JButton PorMateriaButton;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JButton VoltarButton;
    // End of variables declaration//GEN-END:variables
}
